modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/RadialAggroIndicator/issues"
license="MIT"

[[mods]]
modId="radialaggro"
version="${file.jarVersion}"
displayName="Radial Aggro Indicator"
displayURL="https://www.curseforge.com/minecraft/mc-mods/radial-aggro-indicator"
authors="Mrbysco"
credits="NekoMaster for the idea"
description='''
Shows a radial indicator on screen to show the direction of the mob that is currently targeting the player.
'''
[[dependencies.radialaggro]]
modId="minecraft"
type="required"
versionRange="[1.21.11,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.radialaggro]]
modId="neoforge"
type="required"
versionRange="[21.11.0-beta,)"
ordering="NONE"
side="BOTH"